--users table
CREATE TABLE IF NOT EXISTS users (
	id SERIAL PRIMARY KEY,
	username VARCHAR(80) UNIQUE NOT NULL,
	password_hash VARCHAR(255) NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

--Tracker items table
CREATE TABLE IF NOT EXISTS(
	id SERIAL PRIMARY KEY,
	title VARCHAR(200) NOT NULL,
	description TExT,
	category VARCHAR(50),
	completed BOOLENA DEFAULT FALSE,
	position INTEGER,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

